### ISSUE TITLE
Obtain sentience so we don't have to program any more plugins 

### ISSUE THREAD

**Issue by interlock** [vhs/vhsbot#3]

**Comment by seanhagen** [comment]
![](https://c2.staticflickr.com/6/5185/5858071650_e14434116c.jpg)

![](https://pbs.twimg.com/media/BgkxikoIAAASsgn.jpg)

![](http://static2.fjcdn.com/thumbnails/comments/All+these+over+used+jokes+_19168bb396f3e986e6269cf79e4691dc.jpg)

**Comment by interlock** [comment]
Nope. Keep this open, never know right?

**Comment by seanhagen** [comment]
How about not?

**Comment by interlock** [comment]
Dream crusher eh?

**Comment by i-make-robots** [comment]
It's already got us working for it.  We've been outsmarted.

On Thu, Oct 1, 2015 at 1:24 PM, James S notifications@github.com wrote:

> Dream crusher eh?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vhs/vhsbot/issues/3#issuecomment-144793015.

## 

Dan Royer :: Marginally Clever http://www.marginallyclevergroup.com/ ::
Raising Robot Literacy :: +1.604.916.2281
