### ISSUE TITLE
Add a help menu

### ISSUE THREAD

**Issue by JarrettR** [vhs/vhsbot#5]
@vhsbot: help

Include available commands, and also a link to this repo

**Comment by seanhagen** [comment]
the first part already exists.

i can add a command that will tell people where to go, then it'll show up in the help.

**Comment by seanhagen** [comment]
If the help message needs to be changed, let me know. Otherwise will be merging pull request in an hour or so.

**Comment by seanhagen** [comment]
merged #12, closing ticket
